AdminLTE/AdminLTE/Controllers/PESERTAController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdminLTE.Models;

namespace AdminLTE.Controllers
{
    public class PESERTAController : Controller
    {
        private Test_OnlineEntities1 db = new Test_OnlineEntities1();

        // GET: PESERTA
        public ActionResult Index()
        {
            var pESERTA = db.PESERTA.Include(p => p.PROFIL_PESERTA);
            return View(pESERTA.ToList());
        }

        // GET: PESERTA/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PESERTA pESERTA = db.PESERTA.Find(id);
            if (pESERTA == null)
            {
                return HttpNotFound();
            }
            return View(pESERTA);
        }

        // GET: PESERTA/Create
        public ActionResult Create()
        {
            ViewBag.ID_PROFIL = new SelectList(db.PROFIL_PESERTA, "ID_PROFIL", "NAMA_PESERTA");
            return View();
        }

        // POST: PESERTA/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_PESERTA,ID_PROFIL,EMAIL,PASSWORD,Created_by,Created_date,Modified_by,Is_Active")] PESERTA pESERTA)
        {
            if (ModelState.IsValid)
            {
                db.PESERTA.Add(pESERTA);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_PROFIL = new SelectList(db.PROFIL_PESERTA, "ID_PROFIL", "NAMA_PESERTA", pESERTA.ID_PROFIL);
            return View(pESERTA);
        }

        // GET: PESERTA/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PESERTA pESERTA = db.PESERTA.Find(id);
            if (pESERTA == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_PROFIL = new SelectList(db.PROFIL_PESERTA, "ID_PROFIL", "NAMA_PESERTA", pESERTA.ID_PROFIL);
            return View(pESERTA);
        }

        // POST: PESERTA/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_PESERTA,ID_PROFIL,EMAIL,PASSWORD,Created_by,Created_date,Modified_by,Is_Active")] PESERTA pESERTA)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pESERTA).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_PROFIL = new SelectList(db.PROFIL_PESERTA, "ID_PROFIL", "NAMA_PESERTA", pESERTA.ID_PROFIL);
            return View(pESERTA);
        }

        // GET: PESERTA/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PESERTA pESERTA = db.PESERTA.Find(id);
            if (pESERTA == null)
            {
                return HttpNotFound();
            }
            return View(pESERTA);
        }

        // POST: PESERTA/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PESERTA pESERTA = db.PESERTA.Find(id);
            db.PESERTA.Remove(pESERTA);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdminLTE/AdminLTE/Controllers/SOALController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdminLTE.Models;

namespace AdminLTE.Controllers
{
    public class SOALController : Controller
    {
        private Test_OnlineEntities1 db = new Test_OnlineEntities1();

        // GET: SOAL
        public ActionResult Index()
        {
            var sOAL = db.SOAL.Include(s => s.KELOMPOK_SOAL).Include(s => s.TIPE_SOAL).Include(s => s.SUBTES);
            return View(sOAL.ToList());
        }

        // GET: SOAL/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SOAL sOAL = db.SOAL.Find(id);
            if (sOAL == null)
            {
                return HttpNotFound();
            }
            return View(sOAL);
        }

        // GET: SOAL/Create
        public ActionResult Create()
        {
            ViewBag.ID_KELOMPOKSOAL = new SelectList(db.KELOMPOK_SOAL, "ID_KELOMPOKSOAL", "NAMA_KELOMPOKSOAL");
            ViewBag.ID_TIPESOAL = new SelectList(db.TIPE_SOAL, "ID_TIPESOAL", "NAMA_TIPE");
            ViewBag.ID_SUBTES = new SelectList(db.SUBTES, "ID_SUBTES", "Created_by");
            return View();
        }

        // POST: SOAL/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_SOAL,ID_KELOMPOKSOAL,ID_TIPESOAL,ISI_SOAL,NILAI_SOAL,Created_by,Created_date,Modified_by,ID_SUBTES")] SOAL sOAL)
        {
            if (ModelState.IsValid)
            {
                db.SOAL.Add(sOAL);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_KELOMPOKSOAL = new SelectList(db.KELOMPOK_SOAL, "ID_KELOMPOKSOAL", "NAMA_KELOMPOKSOAL", sOAL.ID_KELOMPOKSOAL);
            ViewBag.ID_TIPESOAL = new SelectList(db.TIPE_SOAL, "ID_TIPESOAL", "NAMA_TIPE", sOAL.ID_TIPESOAL);
            ViewBag.ID_SUBTES = new SelectList(db.SUBTES, "ID_SUBTES", "Created_by", sOAL.ID_SUBTES);
            return View(sOAL);
        }

        // GET: SOAL/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SOAL sOAL = db.SOAL.Find(id);
            if (sOAL == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_KELOMPOKSOAL = new SelectList(db.KELOMPOK_SOAL, "ID_KELOMPOKSOAL", "NAMA_KELOMPOKSOAL", sOAL.ID_KELOMPOKSOAL);
            ViewBag.ID_TIPESOAL = new SelectList(db.TIPE_SOAL, "ID_TIPESOAL", "NAMA_TIPE", sOAL.ID_TIPESOAL);
            ViewBag.ID_SUBTES = new SelectList(db.SUBTES, "ID_SUBTES", "Created_by", sOAL.ID_SUBTES);
            return View(sOAL);
        }

        // POST: SOAL/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_SOAL,ID_KELOMPOKSOAL,ID_TIPESOAL,ISI_SOAL,NILAI_SOAL,Created_by,Created_date,Modified_by,ID_SUBTES")] SOAL sOAL)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sOAL).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_KELOMPOKSOAL = new SelectList(db.KELOMPOK_SOAL, "ID_KELOMPOKSOAL", "NAMA_KELOMPOKSOAL", sOAL.ID_KELOMPOKSOAL);
            ViewBag.ID_TIPESOAL = new SelectList(db.TIPE_SOAL, "ID_TIPESOAL", "NAMA_TIPE", sOAL.ID_TIPESOAL);
            ViewBag.ID_SUBTES = new SelectList(db.SUBTES, "ID_SUBTES", "Created_by", sOAL.ID_SUBTES);
            return View(sOAL);
        }

        // GET: SOAL/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SOAL sOAL = db.SOAL.Find(id);
            if (sOAL == null)
            {
                return HttpNotFound();
            }
            return View(sOAL);
        }

        // POST: SOAL/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SOAL sOAL = db.SOAL.Find(id);
            db.SOAL.Remove(sOAL);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdminLTE/AdminLTE/Views/Shared/_ControlSidebar.cshtml
<aside class="control-sidebar control-sidebar-dark">
    @* BEGIN Tabs *@
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    @* END Tabs *@
    <div class="tab-content">
        @* BEGIN Home Tab *@
        <div class="tab-pane active" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript::;">
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
            </ul>

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript::;">
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="pull-right-container">
                                <span class="label label-danger pull-right">70%</span>
                            </span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
            </ul>
        </div>
        @* END Home Tab *@
        <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
        @* BEGIN Settings Tab *@
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Some information about this general settings option
                    </p>
                </div>
            </form>
        </div>
        @* END Settings Tab *@
    </div>
</aside>
@* Add the sidebar's background. This div must be placed immediately after the control sidebar *@
<div class="control-sidebar-bg"></div>

AdminLTE/AdminLTE/Views/Shared/_Header.cshtml
<header class="main-header">
    @* BEGIN Logo *@
    <a href="@Url.Action("Index", "Home")" class="logo">
        @* Mini logo for sidebar 50x50 pixels *@
        <span class="logo-mini"><b>A</b>LT</span>
        @* Logo for regular state and mobile devices *@
        <span class="logo-lg"><b>Admin</b>LTE</span>
    </a>
    @* END Logo *@
    @* BEGIN Header *@
    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                @* BEGIN Messages *@
                <li class="dropdown messages-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-envelope-o"></i>
                        <span class="label label-success">4</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 4 messages</li>
                        <li>
                            <ul class="menu">
                                <li>
                                    <a href="#">
                                        <div class="pull-left">
                                            <img src="~/Content/img/user.jpg" class="img-circle" alt="User Image">
                                        </div>
                                        <h4>
                                            Support Team
                                            <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                        </h4>
                                        <p>Why not buy a new awesome theme?</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer"><a href="#">See All Messages</a></li>
                    </ul>
                </li>
                @* END Messages *@
                @* BEGIN Notifications *@
                <li class="dropdown notifications-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-bell-o"></i>
                        <span class="label label-warning">10</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 10 notifications</li>
                        <li>
                            <ul class="menu">
                                <li>
                                    <a href="#">
                                        <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer"><a href="#">View all</a></li>
                    </ul>
                </li>
                @* END Notifications *@
                @* BEGIN Tasks *@
                <li class="dropdown tasks-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-flag-o"></i>
                        <span class="label label-danger">9</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 9 tasks</li>
                        <li>
                            <ul class="menu">
                                <li>
                                    <a href="#">
                                        <h3>
                                            Design some buttons
                                            <small class="pull-right">20%</small>
                                        </h3>
                                        <div class="progress xs">
                                            @* Change the css width attribute to simulate progress *@
                                            <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                                <span class="sr-only">20% Complete</span>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer">
                            <a href="#">View all tasks</a>
                        </li>
                    </ul>
                </li>
                @* END Tasks *@
                @* BEGIN User Account Menu *@
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="~/Content/img/user.jpg" class="user-image" alt="User Image">
                        <span class="hidden-xs">Alexander Pierce</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="user-header">
                            <img src="~/Content/img/user.jpg" class="img-circle" alt="User Image">

                            <p>
                                Alexander Pierce - Web Developer
                                <small>Member since Nov. 2012</small>
                            </p>
                        </li>
                        <li class="user-body">
                            <div class="row">
                                <div class="col-xs-4 text-center">
                                    <a href="#">Followers</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Sales</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Friends</a>
                                </div>
                            </div>
                        </li>
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a href="#" class="btn btn-default btn-flat">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>
                @* END User Account Menu *@
                @* BEGIN Control Sidebar Toggle Button *@
                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>
                @* END Control Sidebar Toggle Button *@
            </ul>
        </div>
    </nav>
</header>

AdminLTE/AdminLTE/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
@using WebHelpers.Mvc5.Enum
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>
        @if (!string.IsNullOrWhiteSpace(ViewBag.Title))
        {
            @ViewBag.Title@: -
        }
        AdminLTE
    </title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    @Styles.Render("~/Bundles/css")
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        @Html.Partial("_Header")
        @Html.Partial("_Sidebar")

        <div class="content-wrapper">
            <section class="content-header">
                @*<h1>*@
                    @*@ViewBag.Title
                    <small>@ViewBag.Description</small>*@
                @*</h1>*@
            </section>

            <section class="content">
                @RenderBody()
                <hr />
                <footer>
                    <h2>&copy; @DateTime.Now.Year - TES ONLINE</h2>
                </footer>
            </section>
        </div>

        @Html.Partial("_ControlSidebar")
    </div>

    <script src="@RouteJs.RouteJsHandler.HandlerUrl"></script>
    <script src="@EnumHandler.HandlerUrl"></script>
    @Scripts.Render("~/Bundles/js")
    @RenderSection("ViewSpecificJavascript", required: false)
</body>
</html>

AdminLTE/AdminLTE/Views/Shared/_Sidebar.cshtml
@using WebHelpers.Mvc5
<aside class="main-sidebar">
    <section class="sidebar">
        @* BEGIN Search *@
        @*<form action="#" method="get" class="sidebar-form">*@
            @*<div class="input-group">*@
                @*<input type="text" name="q" class="form-control" placeholder="Search...">*@
                @*<span class="input-group-btn">*@
                    @*<button type="submit" name="search" id="search-btn" class="btn btn-flat">*@
                        @*<i class="fa fa-search"></i>*@
                    @*</button>*@
                @*</span>*@
            @*</div>*@
        @*</form>*@
        @* END Search *@
        @* BEGIN Menu *@
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="~/Content/img/user.jpg" class="img-circle" alt="User Image">
                </div>
                <div class="pull-left info">
                    <p>Alexander Pierce</p>
                    <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                </div>
            </div>
            <ul class="sidebar-menu" data-widget="tree">
                <li class="header">MENU ADMIN</li>
                <li class="@Url.IsLinkActive("Index", "Home")">
                    <a href="@Url.Action("Index", "Home")"><i class="fa fa-link"></i> <span>Dashboard</span></a>
                </li>
                
                <li class="treeview">
                    <a href="@Url.Action("Index", "Home")">
                        <i class="fa fa-link"></i> <span>Peserta</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="@Url.Action("Create", "PESERTA")"><i class="fa fa-circle-o"></i>Tambah Peserta</a></li>
                        <li><a href="@Url.Action("Index", "PESERTA")"><i class="fa fa-circle-o"></i>Pilih Peserta</a></li>

                    </ul>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-link"></i> <span>Soal Tes</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="@Url.Action("Create", "SOAL")"><i class="fa fa-circle-o"></i>Tambah Soal</a></li>
                        <li><a href="@Url.Action("Index", "SOAL")"><i class="fa fa-circle-o"></i>Pilih Soal</a></li>

                    </ul>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-link"></i> <span>Jawaban Peserta</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="#">Hasil Jawaban</a></li>
                    </ul>
                </li>
            </ul>
            @* END Menu *@
        </section>
</aside>